# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('url', models.CharField(max_length=2000)),
                ('idUsuario', models.CharField(default='usuario', max_length=20, primary_key=True, serialize=False)),
                ('correo', models.CharField(default='correo@dominio.com', max_length=150)),
                ('nombre', models.CharField(default='nombre', max_length=150)),
                ('paisDeOrigen', models.CharField(default='Colombia', max_length=50)),
                ('ciudad', models.CharField(default='Bogota', max_length=50)),
                ('interesPorLaReserva', models.CharField(default='interes', max_length=500)),
                ('foto', models.ImageField(default='pic_folder/default.jpg', upload_to='pic_folder/')),
            ],
        ),
    ]
